import 'dart:math';
import 'package:flutter/material.dart';

import 'package:projetofelype/Widgets/AllQuoteCard.dart';
import 'package:projetofelype/Widgets/QuoteCard.dart';
import 'package:projetofelype/Domain/frase.dart';
import 'package:projetofelype/api/frase_api.dart';
import 'package:projetofelype/api/frases_fake_api.dart';

import 'homePage.dart';
import 'estatisticasPage.dart';
import 'calendarPage.dart';
import 'pomodoroPage.dart';

import 'lojaRoupinhasPage.dart';

import 'package:projetofelype/db/shared_prefs.dart';
import 'package:projetofelype/pages/loginPage.dart';

class MainPageController extends StatefulWidget {
  const MainPageController({super.key});

  @override
  State<MainPageController> createState() => _MainPageControllerState();
}

class _MainPageControllerState extends State<MainPageController> {
  bool showActions = false;
  int selectedIndex = 0;

  //Início do Menu Navigation Drawer
  List<Frase> listaFrases = [];
  List<Autogenerated> listaFrasesInfluentes = [];
  late Future<List<Frase>> futurelistaFrasesFake;
  late Future<List<Autogenerated>> futureListaFrasesApiReal;

  @override
  void initState() {
    super.initState();
    loadData();
    allfrasesData();
  }

  loadData() async {
    final frases = await FrasesFakeApi().findAll();
    final frasesInfluentes = await FraseApi().findAll();
    setState(() {
      listaFrases = frases;
      listaFrasesInfluentes = frasesInfluentes;
    });
  }

  allfrasesData() async {
    futurelistaFrasesFake = FrasesFakeApi().findAll();
    futureListaFrasesApiReal = FraseApi().findAll();
  }

  void _showRandomFrase() {
    if (listaFrases.isNotEmpty) {
      final random = Random();
      final index = random.nextInt(listaFrases.length);
      final Sorteada = listaFrases[index];
      final SorteadaInfluente = listaFrasesInfluentes[index];

      showDialog(
        context: context,
        barrierDismissible: true,
        barrierColor: Colors.transparent,
        builder: (BuildContext context) {
          return CardFrase(
            frase: Sorteada,
          );
        },
      );
    }
  }

  void _showFrases() async {
    showDialog(
      context: context,
      barrierDismissible: true,
      barrierColor: Colors.transparent,
      builder: (BuildContext context) {
        return Dialog(
          insetPadding: EdgeInsets.all(16),
          backgroundColor: Colors.transparent,
          child: FutureBuilder(
            future: Future.wait([
              FraseApi().findAll(),
              FrasesFakeApi().findAll(),
            ]),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return Center(child: CircularProgressIndicator());
              } else if (snapshot.hasError) {
                return Center(
                  child: Text('Erro ao carregar frases.'),
                );
              } else if (snapshot.hasData) {
                final frasesApiReal = snapshot.data![0] as List<Autogenerated>;
                final frasesApiCriada = snapshot.data![1] as List<Frase>;

                return AllQuoteCard(
                  frases: frasesApiCriada,
                  frasesApiReal: frasesApiReal,
                );
              }
              return SizedBox.shrink();
            },
          ),
        );
      },
    );
  }
  //Fim do Menu Navigation Drawer

  var pages = [
    HomePage(),
    Estatisticas(),
    CalendarPage(),
    PomodoroPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: DefaultTabController(
          length: 4,
          child: Scaffold(
            backgroundColor: Color(0xFFF6FBF7),
            appBar: buildAppBar(),
            drawer: avatarNavigationDrawer(),
            endDrawer: menuNavigationDrawer(
              onShowRandomFrase: _showRandomFrase,
              onShowFrases: _showFrases,
            ),
            body: buildBody(),
            extendBody: true,
            floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
            floatingActionButton: buildFloatingActionButton(),
            bottomNavigationBar: buildBottomNavigationBar(),
          ),
        ),
    );
  }

  buildAppBar() {
    return AppBar(
      //leading: IconButton(onPressed: () {}, icon: Icon(Icons.person_rounded),),
      centerTitle: true,
      backgroundColor: Color(0xFF005E65),
      title: Text(
        'App Name',
        style: TextStyle(
          fontSize: 26,
          color: Colors.black,
          fontWeight: FontWeight.w800,
        ),
      ),
    );
  }

  buildBody() {
    return Stack(
      children: [
        Positioned.fill(child: pages[selectedIndex]),
        if(showActions)
          Positioned.fill(
            child: GestureDetector(
              onTap: (){
                setState(() {
                  showActions = false;
                });
              },

              child: Container(
                color: Colors.black, // translucent overlay
                child: Center(
                  child: Container(
                    padding: EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: Text(
                      'Adicionar nota',
                      style: TextStyle(fontSize: 20, color: Colors.black),
                    ),
                  ),
                ),
              ),
            )
          ),
      ],
    );
  }

  buildFloatingActionButton() {
    return FloatingActionButton(
      onPressed: () {
        setState(() {
          showActions = true;
        });
      },
      elevation: 0,
      backgroundColor: Color(0xFF006A71),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(32.0)),
      foregroundColor: Color(0xFF000000),
      child: const Icon(Icons.add, size: 40.0),
    );
  }

  buildBottomNavigationBar() {
    return BottomNavigationBar(
      currentIndex: selectedIndex,
      onTap: (index) {
        setState(() {
          selectedIndex = index;
        });
      },
      backgroundColor: Color(0xFF006A71),
      unselectedItemColor: Colors.black45,
      selectedItemColor: Colors.black,
      showUnselectedLabels: true,
      type: BottomNavigationBarType.fixed,
      items: const [
        BottomNavigationBarItem(
            icon: Icon(Icons.home_filled),
            label: "Home"
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.bar_chart_rounded),
          label: "Estatísticas",
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.calendar_month_sharp),
          label: "Calendário",
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.access_time_filled),
          label: "Pomodoro",
        ),
      ],
    );
  }
}

class avatarNavigationDrawer extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Drawer(
    backgroundColor: Color(0xFF9ACBD0),
    child: SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[buildHeader(context), buildMenuItems(context)],
      ),
    ),
  );
  Widget buildHeader(BuildContext context) => Container();
  Widget buildMenuItems(BuildContext context) => Container(
    padding: const EdgeInsets.all(24),
    child: Wrap(
      runSpacing: 16,
      children: [
        ListTile(
          leading: const Icon(Icons.person_rounded, color: Color(0xFFFFFFFF)),
          title: const Text(
            'Personalizar Avatar',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: () {},
        ),
        const Divider(color: Color(0xFFFFFFFF)),
        ListTile(
          leading: const Icon(
            Icons.local_grocery_store,
            color: Color(0xFFFFFFFF),
          ),
          title: const Text(
            'Loja de Cosméticos',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => LojaRoupinhasApp(),
              ),
            );
          },
        ),
      ],
    ),
  );
}

class menuNavigationDrawer extends StatelessWidget {
  VoidCallback onShowRandomFrase;
  VoidCallback onShowFrases;

  menuNavigationDrawer({
    required this.onShowRandomFrase,
    required this.onShowFrases,
    super.key,
  });

  @override
  Widget build(BuildContext context) => Drawer(
    backgroundColor: Color(0xFF9ACBD0),
    child: ListView(
      children: <Widget>[buildHeader(context), buildMenuItems(context)],
    ),
  );

  Widget buildHeader(BuildContext context) => Container();

  Widget buildMenuItems(BuildContext context) => Container(
    padding: const EdgeInsets.all(24),
    child: Wrap(
      runSpacing: 16,
      children: [
        ListTile(
          leading:
          const Icon(Icons.person_rounded, color: Color(0xFFFFFFFF)),
          title: const Text(
            'Usuario',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: () {},
        ),
        Divider(color: Color(0xFFFFFFFF)),
        ListTile(
          leading:
          const Icon(Icons.lightbulb_outline, color: Color(0xFFFFFFFF)),
          title: const Text(
            'Frase motivacional',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: onShowRandomFrase,
        ),
        ListTile(
          leading:
          const Icon(Icons.lightbulb_outline, color: Color(0xFFFFFFFF)),
          title: const Text(
            'Frases motivacionais',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: onShowFrases,
        ),
        Divider(color: Color(0xFFFFFFFF)),
        ListTile(
          leading: const Icon(Icons.settings, color: Color(0xFFFFFFFF)),
          title: const Text(
            'Configurações',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: () {},
        ),
        Divider(color: Color(0xFFFFFFFF)),
        ListTile(
          leading: const Icon(
            Icons.logout,
            color: Color(0xFFFFFFFF),
          ),
          title: const Text(
            'Log out',
            style: TextStyle(color: Color(0xFFFFFFFF)),
          ),
          onTap: () {
            SharedPrefs().setUserStatus(false);
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(
                builder: (context) {
                  return LoginPage();
                },
              ),
            );
          },
        ),
        Divider(color: Color(0xFFFFFFFF)),
      ],
    ),
  );
}