import 'package:dio/dio.dart';
import 'package:projetofelype/Domain/frase.dart';

class FraseApi {
  final dio = Dio();
  final baseUrl = "https://zenquotes.io/api/quotes/";

  Future<List<Autogenerated>> findAll() async {
    List<Autogenerated> frasesTraduzidas = [];

    try {
      final response = await dio.get(baseUrl);

      print(response);

      if (response.statusCode == 200) {
        var result = response.data;

        for (var json in result) {
          final frase = Autogenerated.fromJson(json);

          frasesTraduzidas.add(
              Autogenerated(q: frase.q, a: frase.a, c: frase.c, h: frase.h));
        }
      }
    } catch (e) {
      print("Erro ao buscar frases: $e");
    }

    return frasesTraduzidas;
  }
}
