class Autogenerated {
  late String q;
  late String a;
  late String c;
  late String h;

  Autogenerated(
      {required this.q, required this.a, required this.c, required this.h});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    q = json['q'] ?? '';
    a = json['a'] ?? '';
    c = json['c'] ?? '';
    h = json['h'] ?? '';
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['q'] = this.q;
    data['a'] = this.a;
    data['c'] = this.c;
    data['h'] = this.h;
    return data;
  }
}

class Frase {
  late int id;
  late String frase;

  Frase({
    required this.id,
    required this.frase,
  });

  Frase.fromJson(Map<String, dynamic> json) {
    id = json['id'] ?? 0;
    frase = json['frase'] ?? '';
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['frase'] = this.frase;
    return data;
  }
}
