import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:projetofelype/Domain/frase.dart';

class AllQuoteCard extends StatefulWidget {
  final List<Frase> frases;
  final List<Autogenerated> frasesApiReal;

  const AllQuoteCard({
    required this.frases,
    required this.frasesApiReal,
    super.key,
  });

  @override
  State<AllQuoteCard> createState() => _AllQuoteCardState();
}

class _AllQuoteCardState extends State<AllQuoteCard> {
  @override
  Widget build(BuildContext context) {
    return AlertDialog(

      backgroundColor: Colors.white.withOpacity(0.9),
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16.0),
      ),
      content: SizedBox(
        width: double.maxFinite,
        height: 400,
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  const Text(
                    "Mensagens motivacionais",
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Expanded(
                    child: ListView.builder(
                      itemCount: widget.frases.length,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.symmetric(vertical: 6.0),
                          child: Text(
                            widget.frases[index].frase,
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontStyle: FontStyle.italic,
                              height: 1.4,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),

            Container(
              width: 1,
              color: Colors.grey.withOpacity(0.4),
              margin: const EdgeInsets.symmetric(horizontal: 12),
            ),

            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  const Text(
                    "Mensagens de influentes",
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Expanded(
                    child: ListView.builder(
                      itemCount: widget.frasesApiReal.length,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.symmetric(vertical: 6.0),
                          child: Text(
                            widget.frasesApiReal[index].q,
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontStyle: FontStyle.italic,
                              height: 1.4,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
